# Generated by Django 4.2.1 on 2023-10-16 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idcity', models.AutoField(primary_key=True, serialize=False)),
                ('namecity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('idcountry', models.AutoField(primary_key=True, serialize=False)),
                ('namecounty', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('imageprofile', models.ImageField(upload_to='customer/images/')),
                ('address', models.CharField(max_length=300)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country')),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idfreelancer', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('imageprofile', models.ImageField(default='freelancer/images/default-avatar-profile.jpg', upload_to='freelancer/images/')),
                ('imagejobs', models.ImageField(default='freelancer/images/default-image-5-1.jpg', upload_to='freelancer/images/')),
                ('idcity', models.ManyToManyField(to='Freelancer.city')),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country')),
                ('idfreelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('idschedule', models.AutoField(primary_key=True, serialize=False)),
                ('idfreelancer', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservices', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('idrequest', models.AutoField(primary_key=True, serialize=False)),
                ('requestday', models.DateField()),
                ('requesttime', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.customer')),
                ('idfreelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('idneighborhood', models.AutoField(primary_key=True, serialize=False)),
                ('nameneighborhood', models.CharField(max_length=250)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='idneighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.neighborhood'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='idservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.service'),
        ),
        migrations.AddField(
            model_name='customer',
            name='idneighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.neighborhood'),
        ),
        migrations.AddField(
            model_name='city',
            name='idcountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country'),
        ),
    ]
