# Generated by Django 4.2.1 on 2023-08-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nameFreelancer', models.CharField(max_length=300)),
                ('servicios', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='freelancer/images/')),
                ('ubicacion', models.CharField(max_length=250)),
                ('disponibilidad', models.CharField(max_length=250)),
            ],
        ),
    ]
