# Generated by Django 4.2.1 on 2023-09-07 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idcity', models.AutoField(primary_key=True, serialize=False)),
                ('namecity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('idcountry', models.AutoField(primary_key=True, serialize=False)),
                ('namecounty', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('imageprofile', models.ImageField(upload_to='customer/images/')),
                ('address', models.CharField(max_length=300)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('imageprofile', models.ImageField(upload_to='freelancer/images/')),
                ('imagejobs', models.ImageField(upload_to='freelancer/images/')),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('idschedule', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('idservices', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('typeuser', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('idrequest', models.AutoField(primary_key=True, serialize=False)),
                ('registerday', models.DateField()),
                ('state', models.IntegerField()),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.customer')),
                ('idfreelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.freelancer')),
                ('idschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('idneighborhood', models.AutoField(primary_key=True, serialize=False)),
                ('nameneighborhood', models.CharField(max_length=250)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='idfreelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.user'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='idneighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.neighborhood'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='idservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.services'),
        ),
        migrations.AddField(
            model_name='customer',
            name='idcustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='idneighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.neighborhood'),
        ),
        migrations.AddField(
            model_name='city',
            name='idcountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country'),
        ),
    ]
