# Generated by Django 4.2.1 on 2023-09-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('imageprofile', models.ImageField(upload_to='customer/images/')),
                ('address', models.CharField(max_length=300)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.city')),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.country')),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.user')),
                ('idneighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('idrequest', models.AutoField(primary_key=True, serialize=False)),
                ('registerday', models.DateField()),
                ('state', models.IntegerField()),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.customer')),
                ('idfreelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.freelancer')),
                ('idschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.schedule')),
            ],
        ),
    ]
