# Generated by Django 4.2.4 on 2023-09-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0004_alter_customer_idcustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservices', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AddField(
            model_name='schedule',
            name='idfreelancer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='imagejobs',
            field=models.ImageField(default='freelancer/images/default-image-5-1.jpg', upload_to='freelancer/images/'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='imageprofile',
            field=models.ImageField(default='freelancer/images/default-avatar-profile.jpg', upload_to='freelancer/images/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='idservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancer.service'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
