# Generated by Django 4.2.1 on 2023-10-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0005_alter_request_idcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='idcustomer',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='Freelancer.customer'),
        ),
    ]
