# Generated by Django 4.2.1 on 2023-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0006_alter_request_idcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='id',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='idfreelancer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
