# Generated by Django 4.2.4 on 2023-09-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0007_alter_schedule_idfreelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='idfreelancer',
            field=models.IntegerField(default=0),
        ),
    ]
