# Generated by Django 4.2.1 on 2023-10-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0009_freelancer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='idschedule',
        ),
    ]
