# Generated by Django 4.2.1 on 2023-10-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0010_remove_request_idschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idfreelancer', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
