# Generated by Django 4.2.1 on 2023-10-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0011_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='idcustomer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Freelancer.customer'),
        ),
    ]
