# Generated by Django 4.2.1 on 2023-11-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0012_alter_request_idcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
