# Generated by Django 4.2.4 on 2023-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0013_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='latitude',
            field=models.FloatField(default=6.302677225225283),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='length',
            field=models.FloatField(default=-75.56391391880035),
        ),
    ]
